### ISSUE TITLE
Will panic on newer rust due to use of mem::uninitialized creating keypad array

### ISSUE THREAD

**Issue by ghost** [e-matteson/keypad#3]
Hello!

I found this crate from the crater run did in https://github.com/rust-lang/rust/pull/99389 for stricter checks when doing mem::uninitialized.

An uninitialized `keypad::KeypadInput` is being created from inside an array, which is not okay, because references don't allow being left uninitialized (Basically, if it's not a MaybeUninit or zero sized, it doesn't allow being left uninitialized).

The correct way to do this is by using https://doc.rust-lang.org/std/mem/union.MaybeUninit.html, constructing the array inside a MaybeUninit, then at the end, once everything is correctly initialized, using `assume_init`.

Using https://github.com/rust-lang/miri/ might also help detect bugs here.

**Comment by e-matteson** [comment]
Thanks for the report! The fix for this is in PR #4.
